<a href="https://colab.research.google.com/github/Kamal-Minocha/ucs420-/blob/main/assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Question 1: NumPy 1D-array with 5 elements and basic operations

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

add_result = arr + 2
print("a) Addition of 2:", add_result)

mul_result = arr * 3
print("b) Multiply by 3:", mul_result)

div_result = arr / 2
print("c) Divide by 2:", div_result)

Original Array: [10 20 30 40 50]
a) Addition of 2: [12 22 32 42 52]
b) Multiply by 3: [ 30  60  90 120 150]
c) Divide by 2: [ 5. 10. 15. 20. 25.]


### Question 2: Reversing array and finding most frequent values

In [4]:
arr_to_reverse = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr_to_reverse[::-1]
print("a) Reversed array:", reversed_arr)

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def find_frequent_and_indices(array):
    vals, counts = np.unique(array, return_counts=True)
    max_count = np.max(counts)
    most_frequent_vals = vals[counts == max_count]
    results = {}
    for val in most_frequent_vals:
        indices = np.where(array == val)[0]
        results[val] = indices
    return results

print("b) i. For array x:", find_frequent_and_indices(x))
print("b) ii. For array y:", find_frequent_and_indices(y))

a) Reversed array: [5 4 6 3 2 1]
b) i. For array x: {np.int64(1): array([0, 5, 7, 8, 9])}
b) ii. For array y: {np.int64(1): array([0, 1, 2]), np.int64(3): array([4, 8, 9])}


### Question 3: Accessing elements of a 2D array

In [5]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("a) 1st row, 2nd column:", arr_2d[0, 1])
print("b) 3rd row, 1st column:", arr_2d[2, 0])

a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


### Question 4: Linspace array named Kamal_Minocha, attributes, and transpose

In [6]:
Kamal_Minocha = np.linspace(10, 100, 25)
print("Array:", Kamal_Minocha)
print("Dimensions:", Kamal_Minocha.ndim)
print("Shape:", Kamal_Minocha.shape)
print("Total elements:", Kamal_Minocha.size)
print("Data type:", Kamal_Minocha.dtype)
print("Total bytes:", Kamal_Minocha.nbytes)

transpose_reshape = Kamal_Minocha.reshape(1, -1).T
print("Transpose via reshape:\n", transpose_reshape)

transpose_T = Kamal_Minocha.T
print("Transpose via .T:\n", transpose_T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose via reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose via .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


### Question 5: Array manipulations, statistical measures, reshaping and resizing

In [7]:
ucs420_Kamal_Minocha = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Original 2D Array:\n", ucs420_Kamal_Minocha)

print("Mean:", np.mean(ucs420_Kamal_Minocha))
print("Median:", np.median(ucs420_Kamal_Minocha))
print("Max:", np.max(ucs420_Kamal_Minocha))
print("Min:", np.min(ucs420_Kamal_Minocha))
print("Unique elements:", np.unique(ucs420_Kamal_Minocha))

reshaped_ucs420_Kamal_Minocha = ucs420_Kamal_Minocha.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_Kamal_Minocha)

resized_ucs420_Kamal_Minocha = np.resize(ucs420_Kamal_Minocha, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_Kamal_Minocha)

Original 2D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
