<a href="https://colab.research.google.com/github/Kamal-Minocha/ucs420-/blob/main/assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Question 1


In [5]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2 degrees C to every reading using vectorization
temp_corrected = temperature + 2
print("a. Corrected Temperatures (Celsius):", temp_corrected)

# b. Convert all temperatures from Celsius to Fahrenheit
temp_fahrenheit = (9/5) * temperature + 32
print("b. Temperatures in Fahrenheit:", temp_fahrenheit)

# c. Identify all readings greater than 32 degrees C using Boolean indexing
greater_than_32 = temperature[temperature > 32]
print("c. Readings greater than 32 degrees C:", greater_than_32)

# d. Count how many readings exceed 32 degrees C
count_exceeding = np.sum(temperature > 32)
print("d. Count of readings exceeding 32 degrees C:", count_exceeding)

# e. Explanation of vectorization and Boolean indexing efficiency
print("\ne. Explanation:\nVectorization executes operations via optimized, compiled C code under the hood, utilizing SIMD (Single Instruction, Multiple Data) to perform parallel operations on entire arrays at once. This avoids the Python interpreter overhead of loops. Boolean indexing similarly filters elements in a single optimized pass, making data processing significantly faster and more syntactically concise than manually iterating through every single value.")

a. Corrected Temperatures (Celsius): [27 30 33 37 40 29 35 42]
b. Temperatures in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
c. Readings greater than 32 degrees C: [35 38 33 40]
d. Count of readings exceeding 32 degrees C: 4

e. Explanation:
Vectorization executes operations via optimized, compiled C code under the hood, utilizing SIMD (Single Instruction, Multiple Data) to perform parallel operations on entire arrays at once. This avoids the Python interpreter overhead of loops. Boolean indexing similarly filters elements in a single optimized pass, making data processing significantly faster and more syntactically concise than manually iterating through every single value.


### Question 2


In [4]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Calculate the total steps recorded
total_steps = np.sum(steps)
print("a. Total steps recorded:", total_steps)

# b. Calculate the mean number of steps
mean_steps = np.mean(steps)
print("b. Mean number of steps:", mean_steps)

# c. Find the maximum and minimum values
max_steps = np.max(steps)
min_steps = np.min(steps)
print(f"c. Maximum steps: {max_steps}, Minimum steps: {min_steps}")

# d. Calculate the total steps for each day using axis=0
daily_total = np.sum(steps, axis=0)
print("d. Total steps for each day (axis=0):", daily_total)

# e. Calculate the total steps for each user using axis=1
user_total = np.sum(steps, axis=1)
print("e. Total steps for each user (axis=1):", user_total)

# f. Find the user/day position containing the maximum number of steps using argmax()
flat_argmax = np.argmax(steps)
position = np.unravel_index(flat_argmax, steps.shape)
print(f"f. Flat argmax index: {flat_argmax}, Grid position (User, Day): {position}")

a. Total steps recorded: 84200
b. Mean number of steps: 7016.666666666667
c. Maximum steps: 9500, Minimum steps: 4500
d. Total steps for each day (axis=0): [26500 27300 30400]
e. Total steps for each user (axis=1): [18300 24500 14400 27000]
f. Flat argmax index: 11, Grid position (User, Day): (np.int64(3), np.int64(2))


### Question 3


In [6]:
import numpy as np

# a. Create the original array
original = np.array([1, 2, 3, 4, 5, 6])

# b. Create a slice containing elements from index 1 to 4
subset = original[1:4]

# c. Modify the first element of subset to 999
subset[0] = 999
print("c. Original after subset modification:", original)
print("c. Subset:", subset)

# d. Create another slice with .copy()
original = np.array([1, 2, 3, 4, 5, 6]) # reset original
subset_copy = original[1:4].copy()
subset_copy[0] = 500
print("d. Original after copy modification:", original)
print("d. Copied array:", subset_copy)

# e. Create numbers 1 to 12 and reshape into 3 x 4 matrix
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("e. 3x4 Matrix:\n", matrix_3x4)

# f. Indexing and slicing from 3 x 4 matrix
print("f. First row:", matrix_3x4[0])
print("f. Last row:", matrix_3x4[-1])
print("f. Second column:", matrix_3x4[:, 1])
print("f. Elements from rows 1-2 and columns 2-3:\n", matrix_3x4[1:3, 2:4])

# g. Create flattened version using flatten() and ravel()
flat_f = matrix_3x4.flatten()
flat_r = matrix_3x4.ravel()

# h. Modify ravel() and observe original
flat_r[0] = 99
print("h. Original matrix after modifying ravel:", matrix_3x4[0, 0] == 99)

# i. Modify flatten() and observe original
matrix_3x4[0, 0] = 1 # reset
flat_f[0] = 88
print("i. Original matrix after modifying flatten:", matrix_3x4[0, 0] == 88)

# j. Display shape, ndim, size, dtype
print(f"j. Shape: {matrix_3x4.shape}, Ndim: {matrix_3x4.ndim}, Size: {matrix_3x4.size}, Dtype: {matrix_3x4.dtype}")

c. Original after subset modification: [  1 999   3   4   5   6]
c. Subset: [999   3   4]
d. Original after copy modification: [1 2 3 4 5 6]
d. Copied array: [500   3   4]
e. 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. First row: [1 2 3 4]
f. Last row: [ 9 10 11 12]
f. Second column: [ 2  6 10]
f. Elements from rows 1-2 and columns 2-3:
 [[ 7  8]
 [11 12]]
h. Original matrix after modifying ravel: True
i. Original matrix after modifying flatten: False
j. Shape: (3, 4), Ndim: 2, Size: 12, Dtype: int64


### Question 4


In [7]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

# a. Display shape and dimensions of X
print(f"a. Shape of X: {X.shape}, Dimensions of X: {X.ndim}")

# b. Calculate X.T and explanation
XT = X.T
print("b. X.T (Transpose):\n", XT)
print("Explanation: Transpose swaps rows and columns, turning features into rows and users into columns.")

# c. Calculate matrix product X.T @ X
XTX = XT @ X
print("c. X.T @ X:\n", XTX)

# d. Calculate the matrix inverse
XTX_inv = np.linalg.inv(XTX)
print("d. Inverse of (X.T @ X):\n", XTX_inv)

# e. Implement Ordinary Least Squares: beta = (X^T X)^-1 X^T y
beta = XTX_inv @ XT @ y
print("e. Calculated coefficients (beta):", beta)

# f. Explanation of coefficients
print("\nf. Explanation of coefficients:")
print(f"   - Sleep hours coefficient ({beta[0]:.2f}): Change in score per sleep hour.")
print(f"   - Activity level coefficient ({beta[1]:.2f}): Change in score per activity unit.")
print(f"   - Stress level coefficient ({beta[2]:.2f}): Change in score per stress level point.")

# g. Prediction for new user: [5, 40, 7]
new_user = np.array([5, 40, 7])
prediction = new_user @ beta
print(f"\ng. Predicted score for user [5, 40, 7]: {prediction:.2f}")

a. Shape of X: (4, 3), Dimensions of X: 2
b. X.T (Transpose):
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
Explanation: Transpose swaps rows and columns, turning features into rows and users into columns.
c. X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
d. Inverse of (X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
e. Calculated coefficients (beta): [-0.15921454  0.14083853 10.06302242]

f. Explanation of coefficients:
   - Sleep hours coefficient (-0.16): Change in score per sleep hour.
   - Activity level coefficient (0.14): Change in score per activity unit.
   - Stress level coefficient (10.06): Change in score per stress level point.

g. Predicted score for user [5, 40, 7]: 75.28
